title: Comunicóloga Novel
author: erika-martin
email: erika.martin@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Una página en la que aparecerán mis trabajos.

# social links
twitter_username: erika_a_martin # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  erika-martin # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: false # cámbialo a false para eliminar los extractos de la página principal
theme: minima